### PR TITLE
Remove k command and use dnx instead

### PR DESCRIPTION
**Pull request by ChengTian**
https://github.com/aspnet/dnx/issues/1473

### CODE REVIEW

**Comment by hishamco** [comment]
@ChengTian can we make this change in other repositorie that still have the old 'k' command

**Comment by ChengTian** [comment]
@hishamco , if you are talking about other repos under aspnet org, actually I am doing that now: https://github.com/aspnet/dnx/issues/1473

If you are talking about some other repos like your own projects, yes, we are going to remove k.cmd and you should make this change in your own project if you want to use latest DNX runtime.

**Comment by hishamco** [comment]
@ChengTian i was talking about aspnet repos. 
Thanks

**Comment by ChengTian** [comment]
Ah, thanks for offering help :smile: You can also help to review related PRs to make contribution.

**Comment by hishamco** [comment]
@ChengTian Sure

**Comment by hishamco** [comment]
@ChengTian I already added couple of repos that needs the same fix in the issue aspnet/dnx#1473

**Pull request merged**
