### PR TITLE
Updating to new options pattern

### PR DESCRIPTION
**Pull request by JunTaoLuo**
https://github.com/aspnet/Options/issues/105

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
This middleware currently is only configured by options added in DI from `ConfigureServices`. I'm assuming there is no need to add an overload to take an instance of `SessionOptions`.

**Comment by Tratcher** [comment]
Add the UseSession extension that takes new SessionOptions.

**Comment by JunTaoLuo** [comment]
:up::date:

**Comment by Tratcher** [comment]
:shipit:

**Pull request closed without merging**
