### PR TITLE
Update 'dnvmx -x86' switch

### PR DESCRIPTION
**Pull request by hishamco**
@davidfowl @Eilon I made this PR based on the issue #18

### CODE REVIEW

**Comment by davidfowl** [comment]
Changes like these need to be made in *every* repository

**Comment by hishamco** [comment]
@davidfowl I already checked some of the repos seems everything is ok, let me scan them all

**Comment by hishamco** [comment]
@davidfowl I'd like to inform you that I already scanned all the repos, i find 6 repos including this one that they need the same fix. 
Can i made a PR for all of them?

**Comment by davidfowl** [comment]
Yes you can, also update the template in universe https://github.com/aspnet/Universe/tree/dev/build-template

**Comment by hishamco** [comment]
@davidfowl FYI the build.cmd in universe already has the fix

**Comment by Eilon** [comment]
Yeah it looks like @dougbu made the change in lots of repos. Will merge this.

**Pull request merged**
