### PR TITLE
Set the server manually

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
@hishamco I don't think this is the correct fix. Are you trying to run this using `dotnet run` and seeing that a server is missing? If so, that's a known issue and we plan to add the values `"content": ["hosting.json"]` to the `project.json` so that `hosting.json` is copied over when the app is published.

**Comment by hishamco** [comment]
@JunTaoLuo I already use it in localization repo https://github.com/aspnet/Localization/commit/3590cacd3fd26f67c80e8235265e7a8515f5b7e2 and it works fine

**Comment by JunTaoLuo** [comment]
It will work but I think we wanted to keep using `hosting.json` to configure servers.

**Comment by hishamco** [comment]
@Eilon suggested that in https://github.com/aspnet/entropy/pull/76

**Comment by JunTaoLuo** [comment]
I just checked again and it seems some time ago, we decided to remove `hosting.json` and do all the configuration in code instead of what I suggested so this is good :shipit:.

**Comment by JunTaoLuo** [comment]
Thanks @hishamco!

**Comment by Eilon** [comment]
Thanks :smile:

**Pull request merged**
