### PR TITLE
Update SessionDefaults.cs

### PR DESCRIPTION
**Pull request by anandgt2**
Change Default Cookie Name

### CODE REVIEW

**Comment by hishamco** [comment]
I don't think this change will have a good benefit, furthermore there many repos already have the same pattern

**Comment by Tratcher** [comment]
We already made this change in several repoes.

**Comment by hishamco** [comment]
@Tratcher since 6 months back I notice the cookie names has different pattern in several repos, some using underscore and some using dots, any plans to unify them?

**Comment by Tratcher** [comment]
Not yet, but we should. What repos and cookies have you seen?

**Comment by hishamco** [comment]
I notice this in Session & Localization repo, because mainly I contribute on them, but I will try to mention other repos soon

**Comment by hishamco** [comment]
BTW regarding the change the made by @anandgt2 , In which repos is already done, because I didn't expect at first glance it will add a value

**Comment by hishamco** [comment]
FYI this got fixed in PR #98

**Pull request closed without merging**
