### PR TITLE
Add AppVeyor, Travis build status

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by Eilon** [comment]
Actually I just looked at this and the AppVeyor badge URL is wrong. All these build status updates are using the same image URL for AppVeyor. You need to use the `yyivj6uwu3uj2x40` token for this one.

**Comment by hishamco** [comment]
@Eilon that what I notice too, please give me the correct token for each repo

**Comment by Eilon** [comment]
I put the correct token in each PR. As I add more repos I'll mention the token.

**Comment by hishamco** [comment]
thanks @Eilon

**Comment by hishamco** [comment]
A new PR has been created to fix incorrect token

**Pull request merged**
