### PR TITLE
Porting Session from Microsoft.Framework.Cache

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by Eilon** [comment]
:shipit:

**Comment by davidfowl** [comment]
:shipit:

**Comment by davidfowl** [comment]
@pranavkm um what happened? /cc @NTaylorMullen

**Comment by NTaylorMullen** [comment]
Restored dev branch for now to unblock CI, @pranavkm let me know if deleting the dev branch was intentional.

**Comment by pranavkm** [comment]
Woops, didn't realize this was the dev branch.

Sent from my Windows Phone
________________________________

**Pull request closed without merging**
