### PR TITLE
Remove unnecessary 'using'

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by Eilon** [comment]
Merging this one, but please focus on more substantial PRs because this has no significant effect on the code.

**Comment by hishamco** [comment]
Ok @Eilon, but is there a phase for cleaning code and API review?

**Comment by Eilon** [comment]
API reviews are substantial because they affect user experience.

Code cleanup is generally done opportunistically. It would take years to "clean everything up" in every single file in every single repo per all the coding guidelines, but the value just isn't there beyond some reasonable point.

**Comment by hishamco** [comment]
Thanks @Eilon

**Pull request merged**
